CREATE TABLE IF NOT EXISTS `dict` (
  `word` varchar(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`word`)
) CHARSET=utf8;


DELIMITER //
DROP PROCEDURE IF EXISTS GetDict;
CREATE PROCEDURE GetDict()
SQL SECURITY DEFINER
BEGIN
  SELECT word, `description` FROM dict ORDER BY word;
END //
DELIMITER ;


DELIMITER //
DROP PROCEDURE IF EXISTS GetWord;
CREATE PROCEDURE GetWord(_word VARCHAR(255))
SQL SECURITY DEFINER
BEGIN
  SELECT description FROM dict WHERE word = _word;
END //
DELIMITER ;


DELIMITER //
DROP PROCEDURE IF EXISTS SetWord;
CREATE PROCEDURE SetWord(_word VARCHAR(255), _description TEXT)
SQL SECURITY DEFINER
BEGIN
  INSERT INTO dict (word, `description`) VALUES (_word, _description)
    ON DUPLICATE KEY UPDATE `description` = VALUES(description);
END //
DELIMITER ;


DELIMITER //
DROP PROCEDURE IF EXISTS DeleteWord;
CREATE PROCEDURE DeleteWord(_word VARCHAR(255))
SQL SECURITY DEFINER
BEGIN
  DELETE FROM dict WHERE word = _word;
END //
DELIMITER ;
